/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Pubsub_gen.h
  Source: Pubsub_gen.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#ifndef DDSC_PUBSUB_GEN_H
#define DDSC_PUBSUB_GEN_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Pubsub_gen_Msg
{
  char * message;
} Pubsub_gen_Msg;

extern const dds_topic_descriptor_t Pubsub_gen_Msg_desc;

#define Pubsub_gen_Msg__alloc() \
((Pubsub_gen_Msg*) dds_alloc (sizeof (Pubsub_gen_Msg)));

#define Pubsub_gen_Msg_free(d,o) \
dds_sample_free ((d), &Pubsub_gen_Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_PUBSUB_GEN_H */
